export const CATEGORIES: string[] = [
  'INTERIOR', 'EXTERIOR', 'MATERIALS',
  'MATERIALS', 'VEHICLES', 'WEAPONRY',
  'INDUSTRIAL', 'FAUNA', 'CHARACTERS',
  'ANATOMY', 'SPORT', 'OTHER',
  'INDUSTRIAL', 'FAUNA', 'CHARACTERS',
  'ANATOMY', 'SPORT', 'OTHER'
];